### ISSUE TITLE
DSM Let's Encrypt Process

### ISSUE THREAD

**Issue by DiversityBug** [sosandroid/docker-bitwarden_rs-caddy-synology#2]
Hello,
Thank you for this and the fail2ban contribution. The instructions were great and I am able to reach BW through the HTTPS subdomain. Though tinkering with things, it seems I'm not able to get a valid certificate through the DSM process.
Is that even possible? If yes, could you give me some pointers?
Much appreciated!

**Comment by sosandroid** [comment]
My setup let DSM deal with certs and their renewal.

In front of the docker instance, I set the DSM's reverse proxy to deal with HTTPs and pass through the request to Caddy without HTTPS.

This is the way I did it. If Let's encrypt is not able to deliver certs this is because there is no response on ports 80 & 443 when they connect before delivering certs.

Hope this helps

**Comment by DiversityBug** [comment]
Indeed, I was looking at the configuration files where the culprit was my firewall configuration.
Everything is now set up as of the instructions but no ban is happening. - Any other hint there?

**Comment by sosandroid** [comment]
No clues
What are the failtoban logs are saying ?
Did you folow my other tutoriel ?
